name: Check Markdown files

on:
  pull_request:
    paths:
    - '**.md'
    - '.github/workflows/check-markdown-files.yml'
  push:
    branches:
    - 'main'
    paths:
    - '**.md'
    - '.github/workflows/check-markdown-files.yml'

jobs:
  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Run markdownlint-cli2
      uses: DavidAnson/markdownlint-cli2-action@v19
      with:
        globs: |
          **/*.md

  check-links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.6.1
        with:
          fail: true
